# hra-pop
HRA_POP_VERSION : v1.0
HRA_POP_BRANCH : main

# File names
CELL_TYPES_IN_FTUS : cell-types-in-ftus.json
UNIVERSE_FILE_FILENAME : sc-transcriptomics-cell-summaries.jsonl.gz
UNIVERSE_METADATA_FILENAME : sc-transcriptomics-dataset-metadata.csv
ATLAS_FILE_FILENAME : atlas-enriched-dataset-graph.jsonld
UNIVERSE_10K_FILENAME : sc-transcriptomics-cell-summaries.top10k.jsonl.gz
FTU_DATASETS_RAW_FILENAME : ftu-datasets-raw.jsonld
FTU_CELL_SUMMARIES_RAW_FILENAME : ftu-cell-summaries-raw.jsonld
FILTERED_FTU_CELL_TYPE_POPULATIONS_INTERMEDIARY_FILENAME : cell_type_populations_intermediary.jsonl
FILTERED_DATASET_METADATA_FILENAME : filtered-dataset-metadata.json
FTU_DATASETS : ftu-datasets.jsonld
FTU_CELL_SUMMARIES : ftu-cell-summaries.jsonld
ANATOMOGRAMN_METADATA: anatomogram-dataset-metadata.csv
ANATOMOGRAMN_RAW_DATA : anatomogram-raw